### ISSUE TITLE
Crash when trying to load in a world with 1.2.1

### ISSUE THREAD

**Issue by Blobanium** [tr7zw/NotEnoughAnimations#15]
ok so i was playing with my personal modpack and when i updated to 1.2.1 the game started crashing. 
i managed to narrow this down and it seems to be this mod

Crash log:
[crash-2021-03-18_16.24.31-client.txt](https://github.com/tr7zw/NotEnoughAnimations/files/6167732/crash-2021-03-18_16.24.31-client.txt)

using version 1.1.0 works just fine with no crash

tell me if i need anything else thanks

**Comment by Blobanium** [comment]
also this happens then you join a multiplayer server, unsure about singleplayer

**Comment by tr7zw** [comment]
``java.lang.NoSuchMethodError: dev.tr7zw.transliterationlib.api.wrapper.entity.LivingEntity.isClimbing()Z`` You didn't update the TRansliteration lib.
